trigger:
  branches:
    include:
      - main  # Trigger on pushes to main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu agent

steps:
# Install Java 11
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

# Use Maven wrapper or pre-installed Maven
- task: UseMaven@4
  inputs:
    mavenVersionOption: 'Default'
    options: '-X'  # Enable debug output

# Run Maven build and tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-DskipTests=false'  # Run tests

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'  # Adjusted path for Maven Surefire
    testRunTitle: 'Java 11 Unit Tests'
