trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "This is a sample file created by the pipeline." > example.txt
  displayName: 'Create Example File'

- script: cat example.txt
  displayName: 'Display File Contents'
