trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'

- script: mvn clean install -X
  displayName: 'Build and Test with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Java 11 Unit Tests'
