trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
  displayName: 'Set up Java 11'

- script: |
    echo "public class HelloWorld {" > HelloWorld.java
    echo "  public static void main(String[] args) {" >> HelloWorld.java
    echo "    System.out.println(\"This is a sample Java 11 program.\");" >> HelloWorld.java
    echo "  }" >> HelloWorld.java
    echo "}" >> HelloWorld.java
    
    chmod 777 HelloWorld.java

    javac HelloWorld.java
    
    chmod 777 HelloWorld.class
    
    java HelloWorld > example.txt
    
    chmod 777 example.txt
  displayName: 'Compile and Run Java Program with Full Permissions'

- script: cat example.txt
  displayName: 'Display Output File Contents'
